### ISSUE TITLE
Investigate Rollbar Error 69 on ContentTypeParser

### ISSUE THREAD

**Issue by dottorer** [lale-help/lale-help#458] opened 2017-03-13 11:00 UTC
Look into 
https://rollbar.com/lale-help/lale-help/items/69/

**Comment by mkristian** [comment] 2017-03-15 08:31
most probably a duplicate of #460 - let's fix #460 first and see if this pops up again. closing this for now.

**Closed by mkristian** 2017-03-15 08:31 UTC
Labels: bug
